### ISSUE TITLE
Initiator can't send messages to kafka producer

### ISSUE THREAD

**Issue by Dankoy** [Dankoy/jforwarder#340]
**Describe the bug**

Get logs for any api methods (channel, tags) in initiator

```log
Response body: {\"timestamp\":\"2026-08-29T15:42:04.823Z\",\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/api/v1/channel_subscriptions_protobuf\"}

Request body: [{\"channel\":{\"id\":14,\"title\":\"Kiwi \",\"permalink\":\"kiwifruit\"},\"order\":{\"id\":6,\"name\":\"newest\",\"value\":\"most_recent\"},\"scope\":{\"id\":1,\"name\":\"all\"},\"type\":{\"id\":1,\"name\":\"\"},\"chat\":{\"id\":3,\"chatId\":123,\"messageThreadId\":2,\"username\":null},\"coubs\":[{\"id\":1300070017,\"title\":\"Swirl Swirl~\",\"permalink\":\"z33cdwun6v\",\"url\":\"https://coub.com/view/z33cdwun6v\",\"published_at\":\"2026-08-29T13:34:05\"}],\"id\":40,\"lastPermalink\":\"2am9bbaioq\"}]
```

Kafka producer microservice has logs

```log
2026-08-29T15:42:04.822362264Z stdout F 2026-08-29T18:42:04.819+03:00 ERROR 1 --- [nio-8083-exec-2] ERROR [kafka-message-producer,,]o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoClassDefFoundError: Could not initialize class io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema] with root cause
2026-08-29T15:42:04.822536676Z stdout F java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedFile [in thread \"http-nio-8083-exec-3
```

Producer actually tries to send message into kafka, but gets error.

**Expected behavior**
Message should be delivered

**Screenshots**
No

**Additional context**

**Comment by Dankoy** [comment]
# 🐛 Kafka Protobuf Serializer Compatibility Issue

## The Problem

After updating dependencies from release `v1.9.4` to `v1.9.5`, the Kafka message producer started failing with:

```
java.lang.VerifyError: Bad type on operand stack
Type 'com/google/protobuf/DescriptorProtos$FileOptions' is not assignable to 'com/google/protobuf/GeneratedMessage$ExtendableMessage'
```

### Root Cause

The issue was a **transitive dependency conflict** where `com.google.api.grpc:proto-google-common-protos` was being forcibly upgraded from `2.22.1` to `2.70.0`. This version jump introduced incompatible class definitions, causing the `VerifyError` when the Confluent Protobuf serializer tried to use the library at runtime.

The problem was caused by automated dependency updates (Dependabot) that upgraded Spring Boot, Spring Cloud, and other libraries, which pulled in the newer incompatible version.

---

## ✅ Solution 1: Stay on Confluent 7.x (Stable, Minimal Changes)

**Best for:** Production environments that need a quick, low-risk fix.

### Approach
Keep the Confluent serializer on the 7.x line and force a compatible version of `proto-google-common-protos`.

### Implementation

```gradle
dependencies {
    // Use the proven working serializer version
    implementation 'io.confluent:kafka-protobuf-serializer:7.9.0'
    
    // Force compatible Protobuf version
    implementation 'com.google.protobuf:protobuf-java:3.25.5'
    
    // Force compatible proto-google-common-protos version
    implementation('com.google.api.grpc:proto-google-common-protos:2.22.1') {
        force = true
    }
}
```

### ✅ Advantages
- **Proven to work** with Spring Kafka 4.1.0 and Kafka clients 4.2.1
- **No code changes** required
- **Quick fix** - just add dependency constraints
- **Low risk** - uses the same versions that were working in `v1.9.4`

### ❌ Disadvantages
- **Uses older dependencies** (Protobuf 3.x)
- **Missing newer features** from Confluent 8.x
- **Not forward-compatible** with future Spring Boot/Kafka updates

---

## ✅ Solution 2: Full Upgrade to Confluent 8.x (Forward-Compatible)

**Best for:** Long-term projects that want to stay current with the latest versions.

### Approach
Perform a complete migration to the Confluent 8.x line, including recompiling all `.proto` files with the new Protobuf compiler.

### Implementation

1. **Update build configuration**:

```gradle
// Set versions
protobufVersion = '4.34.0'
confluentVersion = '8.3.1'

dependencies {
    // Use the latest Confluent serializer
    implementation "io.confluent:kafka-protobuf-serializer:$confluentVersion"
    
    // Update Protobuf runtime
    implementation "com.google.protobuf:protobuf-java:$protobufVersion"
    
    // Force the version required by Confluent 8.x
    implementation('com.google.api.grpc:proto-google-common-protos:2.53.0') {
        force = true
    }
}

protobuf {
    protoc {
        // Use the same version as protobuf-java
        artifact = "com.google.protobuf:protoc:$protobufVersion"
    }
}
```

2. **Regenerate all `.proto` files**:
```bash
./gradlew clean generateProto
```

3. **Rebuild and test** your application.

### ✅ Advantages
- **Forward-compatible** with Spring Boot and Kafka updates
- **Uses latest features** from Confluent Platform 8.x
- **Works with Kafka 4.2.1** and Spring Kafka 4.1.0
- **Properly aligned** dependencies (all on same major versions)

### ❌ Disadvantages
- **Requires recompilation** of all `.proto` files (must regenerate Java classes)
- **More complex** setup with version constraints
- **Higher risk** due to breaking changes in Protobuf 4.x
- **More time-consuming** to implement and test

---

## 📊 Comparison Table

| Aspect | Solution 1 (7.x) | Solution 2 (8.x) |
|--------|------------------|------------------|
| **Serializers** | `7.9.0` | `8.3.1` |
| **Protobuf Runtime** | `3.25.5` | `4.34.0` |
| **`proto-google-common-protos`** | `2.22.1` | `2.53.0` |
| **Requires `.proto` recompilation** | ❌ No | ✅ Yes |
| **Code changes needed** | ❌ None | ❌ None (just rebuild) |
| **Risk level** | Low | Medium |
| **Time to implement** | Minutes | Hours (includes testing) |
| **Future-compatible** | ❌ No | ✅ Yes |

---

## 🎯 Recommendation

- **If you need a quick fix** for a production issue → Choose **Solution 1**.
- **If you're planning for long-term maintenance** → Choose **Solution 2**.

Both solutions work with **Spring Kafka 4.1.0** and **kafka-clients 4.2.1**. The key difference is whether you want to stay on the proven stable path or invest time in future-proofing your project.

**Comment by Dankoy** [comment]
## Follow-up: how to make this fix stick

#341 aligns everything on the protobuf 4.x line (protobuf-java `4.34.0`, Confluent serializer + Schema Registry `8.3.1`), which is the right call — that's the only Confluent line aligned with Kafka 4.x clients. A note on why the failure looked the way it did, and what protects against a repeat.

### Why it blew up in prod instead of at build time

`ProtobufSchema` is initialized lazily, on the first message. So the classpath was already broken at startup, but nothing noticed until the first HTTP request came in. Also worth knowing for next time: `ExceptionInInitializerError` with the real root cause is logged **once** — every later hit is just `NoClassDefFoundError: Could not initialize class ...` with no useful trace. When debugging, always look for the *earliest* occurrence after pod start.

### Note on the current constraint

```gradle
platform('com.google.api.grpc:proto-google-common-protos:2.53.0')
```

This is a *soft* constraint. It resolves to 2.53.0 today because nothing in the graph currently asks for anything higher — but a plain platform can never downgrade. If a future Spring Boot / Spring Cloud bump reintroduces a module requiring 2.70.0, that will silently win. With protobuf-java 4.34 on the classpath that's most likely harmless (2.70.0 is built against the same protobuf major), so no action is strictly required — but it is not the guarantee it looks like.

If a hard guarantee is wanted, here are the three levels.

---

### Level 1 — a pin that fails loudly

`force` silently substitutes; `platform` silently loses. `strictly` **fails the build** when something in the graph demands a different version:

```gradle
dependencies {
    constraints {
        implementation('com.google.protobuf:protobuf-java') {
            version { strictly protobufVersion }
            because 'Confluent 8.3.1 gencode requires protobuf 4.x; a downgrade causes VerifyError / NoClassDefFoundError'
        }
        implementation('com.google.api.grpc:proto-google-common-protos') {
            version { strictly '2.53.0' }
            because 'must be built against the same protobuf major as the runtime'
        }
    }
}
```

That difference is the whole point: the next Dependabot PR produces an explicit resolution error in CI naming the module that asked for a different version, instead of a green build that dies in production on the first request.

Put this in a shared convention script (next to `protobuf-conventions.gradle`) so it covers consumer and producer at once.

> If `io.spring.dependency-management` is applied, it manages versions outside of Gradle's constraint mechanism. Add `ext['protobuf-java.version'] = protobufVersion` as well.

### Level 2 — dependency locking

Pins the **entire** graph rather than two artifacts. Any transitive version change breaks the build until the lockfile is deliberately regenerated, which makes the drift visible in the PR diff:

```gradle
dependencyLocking { lockAllConfigurations() }

tasks.register('resolveAndLockAll') {
    notCompatibleWithConfigurationCache('resolves configurations at execution time')
    doFirst { assert gradle.startParameter.writeDependencyLocks }
    doLast { configurations.findAll { it.canBeResolved }*.resolve() }
}
```

Regenerate with `./gradlew resolveAndLockAll --write-locks` and commit `gradle.lockfile`.

Cost: every dependency update needs the lockfile regenerated. On a repo with Dependabot that's arguably a feature — you see exactly what moved.

### Level 3 — a smoke test (the important one)

Version pins protect against the *known* breakage. Only actually initializing `ProtobufSchema` during the build protects against the unknown one:

```java
@Test
void protobufSerializerActuallyInitializes() {
    var serializer = new KafkaProtobufSerializer<YourMessage>(new MockSchemaRegistryClient());
    serializer.configure(
        Map.of(AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, "mock://test"), false);

    byte[] bytes = serializer.serialize("topic", YourMessage.newBuilder()./* ... */build());

    assertThat(bytes).isNotEmpty();
}
```

Catches `VerifyError`, `NoClassDefFoundError` and any future misalignment nobody predicted — no Kafka, no Schema Registry, milliseconds, in a plain `./gradlew test`. Manual verification against a running stack proved this fix works; this is what makes the next PR prove it too.

### Optional — an explicit version check

If a readable CI failure is preferred over a resolution stack trace:

```gradle
tasks.register('checkProtobufAlignment') {
    def artifacts = configurations.runtimeClasspath.incoming.artifacts.resolvedArtifacts
    def expected = ['com.google.protobuf:protobuf-java': protobufVersion,
                    'com.google.api.grpc:proto-google-common-protos': '2.53.0']
    doLast {
        def bad = []
        artifacts.get().each { a ->
            def id = a.id.componentIdentifier
            if (id instanceof ModuleComponentIdentifier) {
                if (id.module == 'protobuf-javalite') bad << 'protobuf-javalite on the classpath'
                def key = "${id.group}:${id.module}"
                if (expected[key] && id.version != expected[key])
                    bad << "$key = ${id.version}, expected ${expected[key]}"
            }
        }
        if (bad) throw new GradleException("Protobuf alignment broken:\n" + bad.join('\n'))
    }
}
tasks.named('check') { dependsOn 'checkProtobufAlignment' }
```

---

**If only one of these gets done, make it Level 3.** A version pin guarantees a version; the test guarantees the thing you actually care about — that the serializer comes up.
